export const categories = [
  {
    name: 'Food & Spices',
    icon: '🌶️',
    color: '#FEF3C7',
    text: '#78350F',
    border: '#FDE68A',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Attire & Clothing',
    icon: '👗',
    color: '#FEF9C3',
    text: '#713F12',
    border: '#FEF08A',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Perfumes',
    icon: '🌸',
    color: '#FFEDD5',
    text: '#7C2D12',
    border: '#FED7AA',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Crafts & Art',
    icon: '🎨',
    color: '#F5F5F4',
    text: '#1C1917',
    border: '#E7E5E4',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Jewelry',
    icon: '💎',
    color: '#FDE68A',
    text: '#78350F',
    border: '#FCD34D',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Home Decor',
    icon: '🏺',
    color: '#FEF08A',
    text: '#713F12',
    border: '#FDE047',
    badge: { type: 'sale', color: 'red', content: '15%' },
  },
];

export const featuredProducts = [
  {
    id: '1',
    name: 'Ankara Print Dress',
    price: 15000,
    originalPrice: 18000,
    category: 'Attire',
    rating: 4.8,
    reviews: 124,
    freeDelivery: true,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: '', color: '', content: '' },
  },
  {
    id: '2',
    name: 'Shea Butter Perfume',
    price: 8500,
    originalPrice: 10000,
    category: 'Perfumes',
    rating: 4.9,
    reviews: 98,
    freeDelivery: true,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: 'sale', color: 'green', content: 'New' },
  },
  {
    id: '3',
    name: 'Jollof Rice Mix',
    price: 2500,
    category: 'Food',
    rating: 4.7,
    reviews: 87,
    freeDelivery: false,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: '', color: '', content: '' },
  },
];

export const recommendedProducts = [
  {
    id: '4',
    name: 'Hand-woven Kente Scarf',
    price: 5000,
    category: 'Attire',
    rating: 4.6,
    reviews: 110,
    freeDelivery: true,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: '', color: '', content: '' },
  },
  {
    id: '5',
    name: 'Beaded Maasai Necklace',
    price: 7500,
    category: 'Jewelry',
    rating: 4.9,
    reviews: 205,
    freeDelivery: true,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: 'sale', color: 'blue', content: 'Best Seller' },
  },
  {
    id: '6',
    name: 'Moroccan Lantern',
    price: 9000,
    category: 'Home Decor',
    rating: 4.8,
    reviews: 150,
    freeDelivery: false,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: '', color: '', content: '' },
  },
  {
    id: '7',
    name: 'Spicy Suya Mix',
    price: 1500,
    category: 'Food & Spices',
    rating: 4.5,
    reviews: 75,
    freeDelivery: false,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: '', color: '', content: '' },
  },
];

export const newArrivals = [
  {
    id: '8',
    name: 'Modern Mudcloth Pillow',
    price: 4500,
    category: 'Home Decor',
    rating: 4.9,
    reviews: 88,
    freeDelivery: true,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: 'new', color: 'green', content: 'New' },
  },
  {
    id: '9',
    name: 'Adire Tie-Dye T-Shirt',
    price: 3500,
    category: 'Attire',
    rating: 4.7,
    reviews: 92,
    freeDelivery: true,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: 'new', color: 'green', content: 'New' },
  },
];

export const discountsAndOffers = [
  {
    id: '10',
    name: 'Kenyan Coffee Beans',
    price: 2000,
    originalPrice: 2500,
    category: 'Food & Spices',
    rating: 4.8,
    reviews: 130,
    freeDelivery: false,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: 'discount', color: 'red', content: '20% Off' },
  },
  {
    id: '11',
    name: 'Ghanaian Black Soap',
    price: 1800,
    originalPrice: 2200,
    category: 'Beauty',
    rating: 4.9,
    reviews: 180,
    freeDelivery: true,
    authentic: true,
    image: require('@/assets/images/react-logo.png'),
    badge: { type: 'discount', color: 'red', content: '18% Off' },
  },
];
