export const categories = [
  {
    name: 'Spices',
    icon: '🌶️',
    color: '#FEF3C7',
    text: '#78350F',
    border: '#FDE68A',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Clothing',
    icon: '👗',
    color: '#FEF9C3',
    text: '#713F12',
    border: '#FEF08A',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Perfumes',
    icon: '🌸',
    color: '#FFEDD5',
    text: '#7C2D12',
    border: '#FED7AA',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Art',
    icon: '🎨',
    color: '#F5F5F4',
    text: '#1C1917',
    border: '#E7E5E4',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Jewelry',
    icon: '💎',
    color: '#FDE68A',
    text: '#78350F',
    border: '#FCD34D',
    badge: { type: '', color: '', content: '' },
  },
  {
    name: 'Decor',
    icon: '🏺',
    color: '#FEF08A',
    text: '#713F12',
    border: '#FDE047',
    badge: { type: '', color: '', content: '' },
  },
];

export const products = [
  // Spices
  {
    id: '11111111-1111-1111-1111-111111111111',
    seller_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'West African Suya Spice',
    description: 'A spicy blend for grilling meats, authentic to West Africa.',
    category: 'spices',
    price: 8.99,
    stock_quantity: 120,
    sku: 'SUYA-SPICE-001',
    status: 'active',
    weight: 200.0,
    dimensions: { length: 10, width: 5, height: 3, unit: 'cm' },
    origin_country: 'Nigeria',
    tags: ['spicy', 'grill', 'african', 'meat'],
    images: [
      'https://example.com/images/suya1.jpg',
      'https://example.com/images/suya2.jpg',
    ],
    featured_image: 'https://example.com/images/suya1.jpg',
    rating: 4.7,
    review_count: 23,
    sold_count: 150,
    attributes: {
      spice_level: 'hot',
      ingredients: ['peanuts', 'pepper', 'ginger'],
    },
    created_at: '2024-06-01T12:00:00Z',
    updated_at: '2024-06-01T12:00:00Z',
  },
  {
    id: '11111111-1111-1111-1111-111111111112',
    seller_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    name: 'Ethiopian Berbere Blend',
    description:
      'A fiery, aromatic spice blend essential for Ethiopian cuisine.',
    category: 'spices',
    price: 10.5,
    stock_quantity: 80,
    sku: 'BERBERE-ETH-002',
    status: 'active',
    weight: 150.0,
    dimensions: { length: 8, width: 4, height: 3, unit: 'cm' },
    origin_country: 'Ethiopia',
    tags: ['ethiopian', 'spicy', 'blend'],
    images: [
      'https://example.com/images/berbere1.jpg',
      'https://example.com/images/berbere2.jpg',
    ],
    featured_image: 'https://example.com/images/berbere1.jpg',
    rating: 4.8,
    review_count: 31,
    sold_count: 90,
    attributes: {
      spice_level: 'very hot',
      ingredients: ['chili', 'ginger', 'fenugreek'],
    },
    created_at: '2024-06-02T12:00:00Z',
    updated_at: '2024-06-02T12:00:00Z',
  },
  {
    id: '11111111-1111-1111-1111-111111111113',
    seller_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Moroccan Ras el Hanout',
    description: 'A complex blend of spices for Moroccan tagines and couscous.',
    category: 'spices',
    price: 12.0,
    stock_quantity: 60,
    sku: 'RAS-HANOUT-003',
    status: 'active',
    weight: 120.0,
    dimensions: { length: 7, width: 4, height: 3, unit: 'cm' },
    origin_country: 'Morocco',
    tags: ['moroccan', 'blend', 'tagine'],
    images: [
      'https://example.com/images/ras1.jpg',
      'https://example.com/images/ras2.jpg',
    ],
    featured_image: 'https://example.com/images/ras1.jpg',
    rating: 4.6,
    review_count: 19,
    sold_count: 70,
    attributes: {
      spice_level: 'medium',
      ingredients: ['coriander', 'cumin', 'cinnamon'],
    },
    created_at: '2024-06-03T12:00:00Z',
    updated_at: '2024-06-03T12:00:00Z',
  },
  // Perfumes
  {
    id: '22222222-2222-2222-2222-222222222221',
    seller_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    name: 'Shea Butter Perfume',
    description: 'A soft, natural fragrance with notes of shea and vanilla.',
    category: 'perfumes',
    price: 25.0,
    stock_quantity: 50,
    sku: 'SHEA-PERF-001',
    status: 'active',
    weight: 80.0,
    dimensions: { length: 5, width: 5, height: 12, unit: 'cm' },
    origin_country: 'Ghana',
    tags: ['shea', 'perfume', 'natural'],
    images: [
      'https://example.com/images/shea1.jpg',
      'https://example.com/images/shea2.jpg',
    ],
    featured_image: 'https://example.com/images/shea1.jpg',
    rating: 4.9,
    review_count: 44,
    sold_count: 60,
    attributes: { scent: 'shea, vanilla', longevity: '6h' },
    created_at: '2024-06-04T12:00:00Z',
    updated_at: '2024-06-04T12:00:00Z',
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    seller_id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    name: 'Oud Royal Essence',
    description: 'A luxurious oud-based perfume with deep, woody notes.',
    category: 'perfumes',
    price: 45.0,
    stock_quantity: 30,
    sku: 'OUD-ROYAL-002',
    status: 'active',
    weight: 90.0,
    dimensions: { length: 6, width: 6, height: 14, unit: 'cm' },
    origin_country: 'Egypt',
    tags: ['oud', 'perfume', 'luxury'],
    images: [
      'https://example.com/images/oud1.jpg',
      'https://example.com/images/oud2.jpg',
    ],
    featured_image: 'https://example.com/images/oud1.jpg',
    rating: 4.8,
    review_count: 38,
    sold_count: 40,
    attributes: { scent: 'oud, amber', longevity: '12h' },
    created_at: '2024-06-05T12:00:00Z',
    updated_at: '2024-06-05T12:00:00Z',
  },
  // Jewelry
  {
    id: '33333333-3333-3333-3333-333333333331',
    seller_id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
    name: 'Beaded Maasai Necklace',
    description: 'Handcrafted Maasai necklace with vibrant beads.',
    category: 'jewelry',
    price: 35.0,
    stock_quantity: 40,
    sku: 'MAASAI-NECK-001',
    status: 'active',
    weight: 60.0,
    dimensions: { length: 20, width: 20, height: 2, unit: 'cm' },
    origin_country: 'Kenya',
    tags: ['maasai', 'beaded', 'necklace'],
    images: [
      'https://example.com/images/maasai1.jpg',
      'https://example.com/images/maasai2.jpg',
    ],
    featured_image: 'https://example.com/images/maasai1.jpg',
    rating: 4.9,
    review_count: 55,
    sold_count: 80,
    attributes: { material: 'beads', handmade: true },
    created_at: '2024-06-06T12:00:00Z',
    updated_at: '2024-06-06T12:00:00Z',
  },
  {
    id: '33333333-3333-3333-3333-333333333332',
    seller_id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
    name: 'Tuareg Silver Ring',
    description: 'Traditional Tuareg ring crafted from pure silver.',
    category: 'jewelry',
    price: 60.0,
    stock_quantity: 25,
    sku: 'TUAREG-RING-002',
    status: 'active',
    weight: 20.0,
    dimensions: { length: 3, width: 3, height: 2, unit: 'cm' },
    origin_country: 'Mali',
    tags: ['tuareg', 'silver', 'ring'],
    images: [
      'https://example.com/images/tuareg1.jpg',
      'https://example.com/images/tuareg2.jpg',
    ],
    featured_image: 'https://example.com/images/tuareg1.jpg',
    rating: 4.7,
    review_count: 22,
    sold_count: 30,
    attributes: { material: 'silver', handmade: true },
    created_at: '2024-06-07T12:00:00Z',
    updated_at: '2024-06-07T12:00:00Z',
  },
  // Decor
  {
    id: '44444444-4444-4444-4444-444444444441',
    seller_id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    name: 'Modern Mudcloth Pillow',
    description: 'A stylish pillow featuring traditional mudcloth patterns.',
    category: 'decor',
    price: 22.0,
    stock_quantity: 70,
    sku: 'MUDCLOTH-PILLOW-001',
    status: 'active',
    weight: 400.0,
    dimensions: { length: 45, width: 45, height: 10, unit: 'cm' },
    origin_country: 'Mali',
    tags: ['mudcloth', 'pillow', 'decor'],
    images: [
      'https://example.com/images/mudcloth1.jpg',
      'https://example.com/images/mudcloth2.jpg',
    ],
    featured_image: 'https://example.com/images/mudcloth1.jpg',
    rating: 4.8,
    review_count: 33,
    sold_count: 60,
    attributes: { pattern: 'mudcloth', handmade: true },
    created_at: '2024-06-08T12:00:00Z',
    updated_at: '2024-06-08T12:00:00Z',
  },
  {
    id: '44444444-4444-4444-4444-444444444442',
    seller_id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    name: 'Moroccan Lantern',
    description: 'Handmade lantern with intricate Moroccan patterns.',
    category: 'decor',
    price: 40.0,
    stock_quantity: 35,
    sku: 'MOROCCAN-LANTERN-002',
    status: 'active',
    weight: 900.0,
    dimensions: { length: 25, width: 25, height: 50, unit: 'cm' },
    origin_country: 'Morocco',
    tags: ['lantern', 'moroccan', 'decor'],
    images: [
      'https://example.com/images/lantern1.jpg',
      'https://example.com/images/lantern2.jpg',
    ],
    featured_image: 'https://example.com/images/lantern1.jpg',
    rating: 4.7,
    review_count: 28,
    sold_count: 45,
    attributes: { material: 'metal', handmade: true },
    created_at: '2024-06-09T12:00:00Z',
    updated_at: '2024-06-09T12:00:00Z',
  },
  // Art
  {
    id: '55555555-5555-5555-5555-555555555551',
    seller_id: 'ffffffff-ffff-ffff-ffff-ffffffffffff',
    name: 'Shona Stone Sculpture',
    description: 'A hand-carved sculpture from Zimbabwean Shona stone.',
    category: 'art',
    price: 120.0,
    stock_quantity: 10,
    sku: 'SHONA-SCULPT-001',
    status: 'active',
    weight: 2500.0,
    dimensions: { length: 30, width: 15, height: 40, unit: 'cm' },
    origin_country: 'Zimbabwe',
    tags: ['shona', 'sculpture', 'stone'],
    images: [
      'https://example.com/images/shona1.jpg',
      'https://example.com/images/shona2.jpg',
    ],
    featured_image: 'https://example.com/images/shona1.jpg',
    rating: 4.9,
    review_count: 12,
    sold_count: 15,
    attributes: { material: 'stone', artist: 'Tawanda' },
    created_at: '2024-06-10T12:00:00Z',
    updated_at: '2024-06-10T12:00:00Z',
  },
  {
    id: '55555555-5555-5555-5555-555555555552',
    seller_id: 'ffffffff-ffff-ffff-ffff-ffffffffffff',
    name: 'Ndebele Wall Art',
    description:
      'Colorful wall art inspired by South African Ndebele patterns.',
    category: 'art',
    price: 85.0,
    stock_quantity: 15,
    sku: 'NDEBELE-ART-002',
    status: 'active',
    weight: 700.0,
    dimensions: { length: 60, width: 2, height: 40, unit: 'cm' },
    origin_country: 'South Africa',
    tags: ['ndebele', 'wall art', 'colorful'],
    images: [
      'https://example.com/images/ndebele1.jpg',
      'https://example.com/images/ndebele2.jpg',
    ],
    featured_image: 'https://example.com/images/ndebele1.jpg',
    rating: 4.8,
    review_count: 18,
    sold_count: 20,
    attributes: { style: 'ndebele', handmade: true },
    created_at: '2024-06-11T12:00:00Z',
    updated_at: '2024-06-11T12:00:00Z',
  },
  // Clothing
  {
    id: '66666666-6666-6666-6666-666666666661',
    seller_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Kente Print Dress',
    description:
      'A beautiful traditional Kente print dress for special occasions.',
    category: 'clothing',
    price: 59.99,
    stock_quantity: 30,
    sku: 'KENTE-DRESS-001',
    status: 'active',
    weight: 350.0,
    dimensions: { length: 110, width: 40, height: 2, unit: 'cm' },
    origin_country: 'Ghana',
    tags: ['kente', 'dress', 'traditional', 'african'],
    images: [
      'https://example.com/images/kente1.jpg',
      'https://example.com/images/kente2.jpg',
    ],
    featured_image: 'https://example.com/images/kente1.jpg',
    rating: 4.9,
    review_count: 12,
    sold_count: 40,
    attributes: { occasion: 'wedding', season: 'summer' },
    created_at: '2024-06-12T12:00:00Z',
    updated_at: '2024-06-12T12:00:00Z',
  },
  {
    id: '66666666-6666-6666-6666-666666666662',
    seller_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Adire Tie-Dye T-Shirt',
    description: 'Hand-dyed Adire t-shirt with unique patterns.',
    category: 'clothing',
    price: 35.0,
    stock_quantity: 45,
    sku: 'ADIRE-TSHIRT-002',
    status: 'active',
    weight: 250.0,
    dimensions: { length: 70, width: 50, height: 1, unit: 'cm' },
    origin_country: 'Nigeria',
    tags: ['adire', 't-shirt', 'tie-dye'],
    images: [
      'https://example.com/images/adire1.jpg',
      'https://example.com/images/adire2.jpg',
    ],
    featured_image: 'https://example.com/images/adire1.jpg',
    rating: 4.7,
    review_count: 20,
    sold_count: 30,
    attributes: { style: 'casual', handmade: true },
    created_at: '2024-06-13T12:00:00Z',
    updated_at: '2024-06-13T12:00:00Z',
  },
  {
    id: '66666666-6666-6666-6666-666666666663',
    seller_id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    name: 'Dashiki Shirt',
    description: 'Colorful Dashiki shirt for men and women.',
    category: 'clothing',
    price: 28.0,
    stock_quantity: 60,
    sku: 'DASHIKI-SHIRT-003',
    status: 'active',
    weight: 220.0,
    dimensions: { length: 75, width: 55, height: 1, unit: 'cm' },
    origin_country: 'Senegal',
    tags: ['dashiki', 'shirt', 'african'],
    images: [
      'https://example.com/images/dashiki1.jpg',
      'https://example.com/images/dashiki2.jpg',
    ],
    featured_image: 'https://example.com/images/dashiki1.jpg',
    rating: 4.8,
    review_count: 25,
    sold_count: 50,
    attributes: { style: 'traditional', handmade: true },
    created_at: '2024-06-14T12:00:00Z',
    updated_at: '2024-06-14T12:00:00Z',
  },
  // ...add more products as needed to reach 15-20
];

export const clothingProducts = [
  {
    product_id: '66666666-6666-6666-6666-666666666661',
    clothing_type: 'dress',
    gender: 'female',
    age_group: 'adult',
    sizes_available: ['S', 'M', 'L', 'XL'],
    colors_available: ['red', 'yellow', 'green'],
    material: 'cotton',
    fabric_composition: { cotton: 100 },
    care_instructions: ['Hand wash', 'Do not bleach', 'Iron low'],
    style: 'traditional',
    cultural_significance: 'Kente is a symbol of African heritage and pride.',
    fit_type: 'regular',
  },
  {
    product_id: '66666666-6666-6666-6666-666666666662',
    clothing_type: 't-shirt',
    gender: 'unisex',
    age_group: 'adult',
    sizes_available: ['M', 'L', 'XL'],
    colors_available: ['blue', 'white'],
    material: 'cotton',
    fabric_composition: { cotton: 100 },
    care_instructions: ['Machine wash', 'Do not bleach'],
    style: 'casual',
    cultural_significance: 'Adire is a traditional Yoruba textile art.',
    fit_type: 'regular',
  },
  {
    product_id: '66666666-6666-6666-6666-666666666663',
    clothing_type: 'shirt',
    gender: 'unisex',
    age_group: 'adult',
    sizes_available: ['S', 'M', 'L', 'XL', 'XXL'],
    colors_available: ['multicolor'],
    material: 'cotton',
    fabric_composition: { cotton: 100 },
    care_instructions: ['Hand wash', 'Iron low'],
    style: 'traditional',
    cultural_significance: 'Dashiki is a symbol of African pride.',
    fit_type: 'loose',
  },
];
